# Generated by `dist` (cargo-dist); do not edit by hand.
#
# The release workflow publishes a *complete* formula — version and every sha256 —
# as the `tropism.rb` asset on the GitHub release. `.github/workflows/homebrew-formula.yml`
# prepends this header to that asset and opens an auto-merging pull request, so the
# version and the checksums always arrive in the same commit.
#
# That is why `make release` does not touch this file. A hand-bumped version would
# name tarballs that do not exist yet, and every `brew install` between the bump and
# the end of the build would fail on a checksum mismatch.
#
# The tap is this repository rather than a separate `homebrew-tropism` repo, so the
# tap command needs an explicit URL:
#
#   brew tap grahambrooks/tropism https://github.com/grahambrooks/tropism
#   brew install grahambrooks/tropism/tropism
class Tropism < Formula
  desc "Command-line interface for tropism"
  homepage "https://github.com/grahambrooks/tropism"
  version "2026.9.0"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.0/tropism-aarch64-apple-darwin.tar.xz"
      sha256 "c5f3fe30a054f49063f6d77499016036a6ee8b6ff172cc7e8d4a42c38def2ad0"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.0/tropism-x86_64-apple-darwin.tar.xz"
      sha256 "ca30a2dbb520fc932385d5c284232747c633b7bd673a56e889cc53ecff61c922"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.0/tropism-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "0dcefa93f48f672e695f07636fb40a562ff2303a865cb6ba635b80a51ce0eef4"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.0/tropism-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "80a51db821cd8aff61aaa92d98e4baf67d154faf9da9124c3070420932a32e04"
    end
  end
  license "MIT"

  BINARY_ALIASES = {
    "aarch64-apple-darwin": {},
    "aarch64-unknown-linux-gnu": {},
    "x86_64-apple-darwin": {},
    "x86_64-pc-windows-gnu": {},
    "x86_64-unknown-linux-gnu": {},
    "x86_64-unknown-linux-musl-dynamic": {},
    "x86_64-unknown-linux-musl-static": {}
  }

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "tropism"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "tropism"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "tropism"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "tropism"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
