# Generated by `dist` (cargo-dist); do not edit by hand.
#
# The release workflow publishes a *complete* formula — version and every sha256 —
# as the `tropism.rb` asset on the GitHub release. `.github/workflows/homebrew-formula.yml`
# prepends this header to that asset and opens an auto-merging pull request, so the
# version and the checksums always arrive in the same commit.
#
# That is why `make release` does not touch this file. A hand-bumped version would
# name tarballs that do not exist yet, and every `brew install` between the bump and
# the end of the build would fail on a checksum mismatch.
#
# The tap is this repository rather than a separate `homebrew-tropism` repo, so the
# tap command needs an explicit URL:
#
#   brew tap grahambrooks/tropism https://github.com/grahambrooks/tropism
#   brew install grahambrooks/tropism/tropism
class Tropism < Formula
  desc "Polyglot dependency analyzer that enforces your architecture rules"
  homepage "https://github.com/grahambrooks/tropism"
  version "2026.9.2"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.2/tropism-aarch64-apple-darwin.tar.xz"
      sha256 "f139ae0ba23e213e3062b5ad27bc6b0a2c8cc061f8bc736bb44fafb4582a563c"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.2/tropism-x86_64-apple-darwin.tar.xz"
      sha256 "70eeb4e6b1d0711b6d7da8fd68fa4af0eabd72c0d02f09ecd9704d4c78c7158d"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.2/tropism-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "580055a41982e55a9a45d43ec47d2370fdab12ba19c1147031b7a4ea8105ff9b"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.2/tropism-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "b52f543faf27c8b85445868469b11a55c15a63e909cad2355d3e8bc1f90fcdd1"
    end
  end
  license "MIT"

  BINARY_ALIASES = {
    "aarch64-apple-darwin": {},
    "aarch64-unknown-linux-gnu": {},
    "x86_64-apple-darwin": {},
    "x86_64-pc-windows-gnu": {},
    "x86_64-unknown-linux-gnu": {},
    "x86_64-unknown-linux-musl-dynamic": {},
    "x86_64-unknown-linux-musl-static": {}
  }

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "tropism"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "tropism"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "tropism"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "tropism"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
