# Generated by `dist` (cargo-dist); do not edit by hand.
#
# The release workflow publishes a *complete* formula — version and every sha256 —
# as the `tropism.rb` asset on the GitHub release. `.github/workflows/homebrew-formula.yml`
# prepends this header to that asset and opens an auto-merging pull request, so the
# version and the checksums always arrive in the same commit.
#
# That is why `make release` does not touch this file. A hand-bumped version would
# name tarballs that do not exist yet, and every `brew install` between the bump and
# the end of the build would fail on a checksum mismatch.
#
# The tap is this repository rather than a separate `homebrew-tropism` repo, so the
# tap command needs an explicit URL:
#
#   brew tap grahambrooks/tropism https://github.com/grahambrooks/tropism
#   brew install grahambrooks/tropism/tropism
class Tropism < Formula
  desc "Polyglot dependency analyzer that enforces your architecture rules"
  homepage "https://github.com/grahambrooks/tropism"
  version "2026.9.1"
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.1/tropism-aarch64-apple-darwin.tar.xz"
      sha256 "06d2f173a98dfc15d93943265bc07ad168770b70a9f976d71a553e63484d14f6"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.1/tropism-x86_64-apple-darwin.tar.xz"
      sha256 "b68397fe86601b004e2e11bd1a4bbcff9e4fb5b99b6eb2bc62c32225c406ccb9"
    end
  end
  if OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.1/tropism-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "5f4e5c8d8fbe2d85be731b6c805891d08f735577eda68e044b90cf4ba0831f32"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grahambrooks/tropism/releases/download/v2026.9.1/tropism-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "d5d52fc5a8eafd07b2e88a0d1754441714623e2acae90e3c12ccda2479c8bfbc"
    end
  end
  license "MIT"

  BINARY_ALIASES = {
    "aarch64-apple-darwin": {},
    "aarch64-unknown-linux-gnu": {},
    "x86_64-apple-darwin": {},
    "x86_64-pc-windows-gnu": {},
    "x86_64-unknown-linux-gnu": {},
    "x86_64-unknown-linux-musl-dynamic": {},
    "x86_64-unknown-linux-musl-static": {}
  }

  def target_triple
    cpu = Hardware::CPU.arm? ? "aarch64" : "x86_64"
    os = OS.mac? ? "apple-darwin" : "unknown-linux-gnu"

    "#{cpu}-#{os}"
  end

  def install_binary_aliases!
    BINARY_ALIASES[target_triple.to_sym].each do |source, dests|
      dests.each do |dest|
        bin.install_symlink bin/source.to_s => dest
      end
    end
  end

  def install
    if OS.mac? && Hardware::CPU.arm?
      bin.install "tropism"
    end
    if OS.mac? && Hardware::CPU.intel?
      bin.install "tropism"
    end
    if OS.linux? && Hardware::CPU.arm?
      bin.install "tropism"
    end
    if OS.linux? && Hardware::CPU.intel?
      bin.install "tropism"
    end

    install_binary_aliases!

    # Homebrew will automatically install these, so we don't need to do that
    doc_files = Dir["README.*", "readme.*", "LICENSE", "LICENSE.*", "CHANGELOG.*"]
    leftover_contents = Dir["*"] - doc_files

    # Install any leftover files in pkgshare; these are probably config or
    # sample files.
    pkgshare.install(*leftover_contents) unless leftover_contents.empty?
  end
end
