<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Shop.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shop.Domain\Shop.Domain.csproj" />
    <ProjectReference Include="..\Shop.Data\Shop.Data.csproj" />
  </ItemGroup>
</Project>
